### ISSUE TITLE
ValueError: Expected input batch_size (40) to match target batch_size (44).

### ISSUE THREAD

**Issue by jskbliy** [feizc/Future-Caption#3]
NAICModel:   0%|          | 1277/414113 [00:50<4:28:58, 25.58it/s, loss=6.72]Traceback (most recent call last):
  File "/media/cs/D4FA828F299D817A/Future-Caption-main/train_naic.py", line 132, in <module>
    main()
  File "/media/cs/D4FA828F299D817A/Future-Caption-main/train_naic.py", line 119, in main
    train_loss = train(model, train_dataloader, args, optimizer, scheduler, epoch, tokenizer)
  File "/media/cs/D4FA828F299D817A/Future-Caption-main/train_naic.py", line 49, in train
    loss = nnf.cross_entropy(outputs.reshape(-1, outputs.shape[-1]), labels.flatten(), ignore_index=-1)
  File "/home/cs/anaconda3/envs/future/lib/python3.7/site-packages/torch/nn/functional.py", line 3014, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (40) to match target batch_size (44).
NAICModel:   0%|          | 1278/414113 [00:50<4:32:33, 25.24it/s, loss=6.72]

**Comment by SZW-zjbd** [comment]
hi，i want to ask where is 'inference.py' i can not find
